# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Point to the new location of the configuration file
sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
