# .readthedocs.yaml
# Configuration file for Read the Docs.

# Required
version: 2

# Set the version of Python to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Define how to build the documentation
sphinx:
  configuration: docs/conf.py

# Define how to install your project and its dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs