# .github/workflows/release.yml

name: Build and Publish to PyPI

# This workflow runs on every push to the main branch and when a release is created.
on:
  push:
    branches:
      - main
      - master
  release:
    types: [created]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Build on all major platforms
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # A version to run cibuildwheel

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # This is the crucial step: skip all PyPy builds.
          # The "*" is a wildcard, so this skips pp38, pp39, etc.
          CIBW_SKIP: "pp*"
          # To build for ARM on macOS, you can add:
          # CIBW_ARCHS_MACOS: "x86_64 arm64"

      - name: Store wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse

  publish_wheels:
    name: Publish wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    # This job runs only when a new release is created on GitHub
    if: github.event_name == 'release' && github.event.action == 'created'

    # Set up trusted publishing
    permissions:
      id-token: write # This is required for trusted publishing

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          # The pattern matches the artifact names from the build jobs
          pattern: wheels-*
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # The 'dist' directory now contains all the wheels from all OSs
          packages-dir: dist/

