# .github/workflows/release.yml

name: Build and Publish to PyPI

# This workflow runs on every push to the main branch and when a release is created.
on:
  push:
    branches:
      - main
      - master
  release:
    types: [created]

jobs:
  build_wheels:
    name: Build Linux wheels
    runs-on: ubuntu-latest # Run only on Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # A version to run cibuildwheel

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # The configuration in pyproject.toml will be used automatically.

      - name: Store wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: ./wheelhouse

  publish_wheels:
    name: Publish wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    # This job runs only when a new release is created on GitHub
    if: github.event_name == 'release' && github.event.action == 'created'

    # Set up trusted publishing
    permissions:
      id-token: write # This is required for trusted publishing

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          # The pattern matches the artifact name from the build job
          pattern: linux-wheels
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

